name: "Build Docker Images"
on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      image_name:
        type: string
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      subdir:
        default: '.'
        type: string
      solr:
        description: "Use if you need to build a specific Solr image and push to the registry"
        required: false
        type: boolean
      solrTarget:
        required: false
        type: string
      tag:
        required: false
        type: string
      target:
        required: false
        type: string
      worker:
        required: false
        type: boolean
      workerTarget:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/ams/workflows/setup-env@action.yaml
        # uses: WGBH-MLA/ams/workflows/setup-env@action.yaml
        with:
          tag: ${{ inputs.tag }}
          image_name: ${{ inputs.image_name }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up build
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull web || true
      - name: Retag action for web
        id: meta-web
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for worker
        if: ${{ inputs.worker }}
        id: meta-worker
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for solr
        if: ${{ inputs.solr }}
        id: meta-solr
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push web
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-web.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          target: ${{ inputs.target }}
      - name: Build and push worker
        if: ${{ inputs.worker }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-worker.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
          target: ${{ inputs.workerTarget }}
      - name: Build and push solr
        if: ${{ inputs.solr }}
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:${{ env.TAG }}
          context: ./solr
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-solr.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:${{ env.TAG }}
          target: ${{ inputs.solrTarget }}